# fly.toml app configuration file generated for capstone-2 on 2025-01-02T18:47:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teamShyft'
primary_region = 'iad'

[build]

[[static_sites]]
  backend = "static"
  source = "./dist"  # Ensure this path points to your Vite build directory
  fallback = "/index.html"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
