app = "my-vite-spa"

[build]
image = "dockerfile"  # Tells Fly to use your Dockerfile

[[services]]
internal_port = 8080
processes = ["app"]

[[services.ports]]
handlers = ["http"]
port     = 80

[[services.ports]]
handlers = ["tls", "http"]
port     = 443
